### ISSUE TITLE
Support specifying update versions

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/setup-ballerina#15]
### Current Limitation

Most of the time, we want to make sure the package written on a specific ballerina version to be compatible with its corresponding update version. For example, a ballerina package written in update `2201.10.0` should be compatible with all the patch version of update 10 - `2201.10.1`, `2201.10.2` etc. Currently, we cannot specify just the update version in the action.

### Suggested Improvement

Allow configuring update version in the action. Following are few suggestions on the configuration:

1. ```yml
    name: Set Up Ballerina
    uses: ballerina-platform/setup-ballerina@v1.1.3
    with:
       version: '2201.10.*'
    ```

2. ```yml
    name: Set Up Ballerina
    uses: ballerina-platform/setup-ballerina@v1.1.3
    with:
       version: '2201.10'
    ```

3. ```yml
    name: Set Up Ballerina
    uses: ballerina-platform/setup-ballerina@v1.1.3
    with:
       version: 'update-10'
    ```

### Version

1.1.3
