### ISSUE TITLE
Action fails to properly install Ballerina for Windows builds

### ISSUE THREAD

**Issue by Xenowa** [ballerina-platform/setup-ballerina#6]
**Description:**
The setup-ballerina action works as expected when a numeric version is provided in the workflow file as `version: '2201.8.6'`, however it fails when `version:latest` is provided.

#### Potential Fix:
Change the [`steps.configure-version.outputs.version`](https://github.com/ballerina-platform/setup-ballerina/blob/main/action.yml#L54C39-L54C78) to [`inputs.version`](https://github.com/ballerina-platform/setup-ballerina/blob/main/action.yml#L39C216-L39C230)

**Suggested Labels:**
Bug

**Steps to reproduce:**
1. Create a repository with a workflow file containing setup-ballerina action for Windows.
```yml
name: Test Setup Ballerina Action

on:
  push:

jobs:
  windows_build:
    name: Build
    runs-on: windows-latest
    concurrency:
      group: ${{ github.head_ref }}-windows
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.0.7'

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest
```

2. Trigger workflow by pushing changes to repository

Here is the build stacktrace:
```
Run ballerina-platform/setup-ballerina@v1.1.0
Run if [[ latest == 'latest' ]]; then
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    60  100    60    0     0    265      0 --:--:-- --:--:-- --:--:--   26[7](https://github.com/Xenowa/static-code-analysis-tool/actions/runs/8445859934/job/23133714973#step:4:8)
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[20](https://github.com/Xenowa/static-code-analysis-tool/actions/runs/8445859934/job/23133714973#step:4:22)[22](https://github.com/Xenowa/static-code-analysis-tool/actions/runs/8445859934/job/23133714973#step:4:24)-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Run actions/cache@v3
Cache not found for input keys: ballerina-2201.8.6-Windows
Run set -x
+ [[ msys == \m\s\y\s* ]]
windows runner detected
+ echo 'windows runner detected'
+ curl -L -S -s https://dist.ballerina.io/downloads/2201.8.6/ballerina-2201.8.6-swan-lake-windows-x64.msi --output ballerina-latest-swan-lake-windows-x64.msi
Run set -x
+ [[ msys == \m\s\y\s* ]]
+ echo 'windows runner detected'
+ msiexec //i ballerina-2201.8.6-swan-lake-windows-x64.msi //qn
windows runner detected
This installation package could not be opened.  Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package.


Error: Process completed with exit code [83](https://github.com/Xenowa/static-code-analysis-tool/actions/runs/8445859934/job/23133714973#step:4:88).
```
